/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
	aws_project_region: 'us-west-2',
	aws_cognito_region: 'us-west-2',
	aws_user_pools_id: 'us-west-2_yT4PGG5bO',
	aws_user_pools_web_client_id: '240oetneeaccrkkhiljrjmvdhd',
	oauth: {},
	aws_cognito_username_attributes: ['EMAIL'],
	aws_cognito_social_providers: [],
	aws_cognito_signup_attributes: [],
	aws_cognito_mfa_configuration: 'OFF',
	aws_cognito_mfa_types: [],
	aws_cognito_password_protection_settings: {
		passwordPolicyMinLength: 8,
		passwordPolicyCharacters: ['REQUIRES_LOWERCASE', 'REQUIRES_UPPERCASE', 'REQUIRES_NUMBERS'],
	},
	aws_cognito_verification_mechanisms: ['EMAIL'],
}

const awsMobile2 = {
	aws_project_region: 'us-west-2',
	aws_cognito_region: 'us-west-2',
	aws_user_pools_id: 'us-west-2_yT4PGG5bO',
	aws_user_pools_web_client_id: '240oetneeaccrkkhiljrjmvdhd',
	oauth: {
		domain: 'auth.charmed.ai',
		scope: ['profile', 'email', 'openid', 'aws.cognito.signin.user.admin'],
		redirectSignIn: 'http://localhost:4321',
		redirectSignOut: 'http://localhost:4321',
		responseType: 'code',
	},
	federationTarget: 'COGNITO_USER_POOLS',
	aws_cognito_username_attributes: ['EMAIL'],
	aws_cognito_social_providers: ['GOOGLE'],
	aws_cognito_signup_attributes: [],
	aws_cognito_mfa_configuration: 'OFF',
	aws_cognito_mfa_types: [],
	aws_cognito_password_protection_settings: {
		passwordPolicyMinLength: 8,
		passwordPolicyCharacters: ['REQUIRES_LOWERCASE', 'REQUIRES_UPPERCASE', 'REQUIRES_NUMBERS'],
	},
	aws_cognito_verification_mechanisms: ['EMAIL'],
}

export default awsMobile2
